[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D SSID_AP='"ESP32 LOCAL"'
    -D PASS_AP='"12345678"'
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -D MQTT_MAX_PACKET_SIZE=1024

lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32@1.0.0
    adafruit/Adafruit NeoPixel@^1.15.1
    DHT20
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2
    ayushsharma82/ElegantOTA@^3.1.7
    ESP32Async/AsyncTCP@^3.3.7
    ESP32Async/ESPAsyncWebServer@^3.7.3

lib_compat_mode = strict
